### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by ronaldyuwandika**
This PR is for fixing this issue #1

What I do:

- add Attribution-NonCommercial-ShareAlike 4.0 International License

### CODE REVIEW

**Comment by erikkroes** [comment]
Thank you so much! Could you make it a .md-file? So LICENSE.md?

**Comment by ronaldyuwandika** [comment]
sure :) I will fix it on next commits

**Comment by erikkroes** [comment]
Perfect, thanks!

**Comment by ronaldyuwandika** [comment]
Your Welcome :))

**Pull request merged**
